### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by MonzterDev** [MoSadie/AwayFromAuction#1]
This Mod looks great and offers such a needed and unique feature, but I was wondering how do I install it? I cannot find the Executable Jar File.

**Comment by MoSadie** [comment]
Thanks for the interest! I still need to do some final polishing and code cleanup before I feel comfortable making a complete release with the jar file. When I do post it, you can find the download information [here](https://github.com/MoSadie/AwayFromAuction/releases) and I'll post another comment on this issue. (Should be done within a day or two)

Just to be clear, the jar itself is not an executable (as in you click to launch), it's a Minecraft Forge 1.14.4 mod.

**Comment by MoSadie** [comment]
v1.0.0 has been released! [Link](https://github.com/MoSadie/AwayFromAuction/releases/tag/v1.0.0) to the release.
