### ISSUE TITLE
Minecraft 1.8.9

### ISSUE THREAD

**Issue by konoashi** [MoSadie/AwayFromAuction#4]
Add version for minecraft 1.8.9 cause literally nobody use the 1.14

**Comment by MoSadie** [comment]
I'm already working on it! You can subscribe to notifications on issue #3 to be notified when I finish it. Right now I have the main features working, just need to fix a few bugs and clean everything up.

**Comment by konoashi** [comment]
thx so much

**Comment by MoSadie** [comment]
Done! Check out [v1.0.1](https://github.com/mosadie/awayfromauction/releases/v1.0.1).
